[project]
name = "hf-rocm-kernels"
version = "0.1.0"
authors = []
license = { text = "Apache 2.0" }
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
]

dependencies = [
    "amdsmi>=6.2.0",
    "numpy<2.0.0",
    "torch>=2.5.0",
    "pytorch-triton-rocm>=3.0.0",
]

[build-system]
requires = [
    "cmake>=3.26",
    "numpy<2.0.0",
    "setuptools>=61",
    "torch>=2.5.0",
    "pytorch-triton-rocm>=3.0.0",
]

[dependency-groups]
dev = [
    "clang-format>=19.0.0",
    "pytest>=8.3.3",
    "ruff>=0.8.0",
    "matplotlib>=3.7.0",
]

[tool.uv.sources]
torch = { index = "pytorch-rocm" }
torchvision = { index = "pytorch-rocm" }
pytorch-triton-rocm = { index = "pytorch-rocm" }


[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.2"
explicit = true
